# Generated by Django 5.1.1 on 2024-09-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="performance_date",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="performance_time",
        ),
        migrations.AddField(
            model_name="entitiesmaster",
            name="performance_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
