# Generated by Django 5.1.1 on 2024-09-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_entitiesmaster_performance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitiesmaster",
            name="url",
            field=models.URLField(default="", max_length=255),
        ),
    ]
