# Generated by Django 5.1.1 on 2024-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_entitiesmaster_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntitiesMaster1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("concert_title", models.CharField(max_length=255)),
                ("performance_datetime", models.DateTimeField(null=True)),
                ("performance_dow", models.CharField(max_length=10)),
                ("venue", models.CharField(max_length=255)),
                ("artist_name", models.CharField(max_length=255)),
                (
                    "artist_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("composer", models.CharField(max_length=255)),
                ("piece", models.CharField(max_length=255)),
                ("url", models.URLField(default="", max_length=255)),
            ],
            options={
                "db_table": "EntitiesMaster1",
            },
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="artist_name",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="artist_role",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="composer",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="performance_datetime",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="performance_dow",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="piece",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="url",
        ),
        migrations.RemoveField(
            model_name="entitiesmaster",
            name="venue",
        ),
        migrations.AddField(
            model_name="entitiesmaster",
            name="concert_info",
            field=models.JSONField(default={}),
        ),
    ]
