# Generated by Django 5.1.1 on 2024-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_entitiesmaster1_remove_entitiesmaster_artist_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitiesmaster",
            name="url",
            field=models.URLField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="entitiesmaster",
            name="concert_info",
            field=models.JSONField(default=dict),
        ),
    ]
