# Generated by Django 5.1.1 on 2024-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_entitiesmaster_url_alter_entitiesmaster_concert_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitiesmaster",
            name="url",
            field=models.URLField(default="", max_length=255, unique=True),
        ),
    ]
